df.fontsize = 12;
df.fontname = 'Arial';

set(0,'DefaultFigureWindowStyle','normal',...
      'DefaultAxesFontName',df.fontname,...
      'DefaultAxesFontSize', df.fontsize, ...
      'DefaultAxesFontAngle', 'normal', ...
      'DefaultAxesFontWeight', 'normal', ...
      'DefaultAxesFontSizeMode', 'manual', ...
      'DefaultAxesLabelFontSizeMultiplier', 1,...
      'DefaultAxesTitleFontWeight', 'bold', ...
      'DefaultAxesTitleFontSizeMultiplier', 1,...
      'FixedWidthFontName',df.fontname,...
      'DefaultTextFontName',df.fontname,...
      'DefaultAxesFontSize', df.fontsize, ...
      'DefaultTextboxshapeFontName',df.fontname,...
      'DefaultTextboxshapeFontSize', df.fontsize, ...
      'DefaultTextarrowshapeFontName',df.fontname,...
      'DefaultTextarrowshapeFontSize', df.fontsize, ...
      'DefaultPolaraxesFontName',df.fontname,...
      'DefaultPolaraxesFontSize', df.fontsize, ...
      'DefaultLegendFontName',df.fontname,...
      'DefaultLegendFontSize', df.fontsize, ...
      'DefaultColorbarFontName',df.fontname,...
      'DefaultColorbarFontSize', df.fontsize, ...
      'DefaultTextFontSize', df.fontsize,...
      'defaultfigurecolor', 'w');

clear df

